# (c) Copyright IBM Corp. 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
collections:
  - name: ibm.ibm_zos_core
    version: 1.6.0
  - name: operator_sdk.util
    version: 0.5.0
  - name: kubernetes.core
    version: 2.4.0
