# (c) Copyright IBM Corp. 2023,2024
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Validate user inputs
  environment: "{{ z_environment_vars }}"
  validate_inputs:
    sys_id: "{{ DFH_REGION_SYSID }}"
    applid: "{{ DFH_REGION_APPLID }}"
    zfs_path: "{{ DFH_ZFS_MOUNTPOINT }}"
    user: "{{ USER }}"
    pyz: "{{ DFH_ZOS_PYTHON_PATH }}"
    zoau: "{{ ZOAU }}"
    dfltuser: "{{ DFH_REGION_DFLTUSER }}"
    region_hlq: "{{ DFH_REGION_HLQ }}"
    le_hlq: "{{ DFH_LE_HLQ }}"
    cics_hlq: "{{ DFH_CICS_HLQ }}"
    cics_license: "{{ DFH_CICS_LICENSE_DATA_SET }}"
    cics_usshome: "{{ DFH_CICS_USSHOME }}"
    cpsm_hlq: "{{ DFH_CPSM_HLQ }}"
    cmci_port: "{{ DFH_CMCI_PORT | int }}"
  register: validation_result

- name: Validate the config properties specified
  ansible.builtin.shell:
    cmd: |
      {{ lookup('template', 'validateConfigProperties.sh.j2') }}
  changed_when: false
  environment: "{{ z_environment_vars }}"
