# (c) Copyright IBM Corp. 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
argument_specs:
  main:
    short_description: Submit a z/OS job after applying a template
    options:
      z_environment_vars:
        type: dict
        required: true
      zos_job_submit_template_src:
        type: str
        required: true
        description: Path to the JCL template
      zos_job_submit_template_max_rc:
        type: int
        required: false
        default: 0
      zos_job_submit_template_wait_time_s:
        type: int
        required: false
        default: 180
