# (c) Copyright IBM Corp. 2023,2024
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
name: zos-cics-ts-operator
displayName: CICS TS Operator
domain: ibm
version: 2.1.0
description: >-
  # CICS TS Operator
    The **IBM CICS TS Operator Collection** provides automation around provisioning CICS Transaction Server for z/OS to one or more z/OS endpoints and
    managing its lifecycle in a hybrid cloud environment.
  # Input
    IBM CICS TS Operator provides support for all in-service releases of CICS TS. You can provision a CICS TS region at a release level of your choice.
    The actual release level that gets provisioned depends on the value of HLQ for CICS load libraries and the CICS SVC that you have specified for the
    z/OS endpoint. You must ensure that you are pointing to the correct libraries for the release of your CICS installation.
    You can provision a CICS TS region as a CICS System Management Single Server (SMSS). An SMSS contains the CICS management client interface (CMCI).
    To provision an SMSS, you must set the HLQ for CICSPlex SM data sets and CMCI port parameters when you create a CICS TS instance. By default,
    IBM CICS TS Operator provisions a stand-alone CICS region, which does not have the CMCI component.
  # Version
    Check the [release notes](https://www.ibm.com/docs/SSV97FN_latest/cics-operator/release-notes.html) for the latest information about versions of this
    Operator Collection.
icon:
  - base64data: >-
      PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDI2LjAuMSwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkNSVUlTRSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiCgkgd2lkdGg9IjMycHgiIGhlaWdodD0iMzJweCIgdmlld0JveD0iMCAwIDMyIDMyIiBzdHlsZT0iZW5hYmxlLWJhY2tncm91bmQ6bmV3IDAgMCAzMiAzMjsiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8c3R5bGUgdHlwZT0idGV4dC9jc3MiPgoJLnN0MHtmaWx0ZXI6dXJsKCNBZG9iZV9PcGFjaXR5TWFza0ZpbHRlcik7fQoJLnN0MXtmaWxsOiNGRkZGRkY7fQoJLnN0MntmaWxsOnVybCgjU1ZHSURfMDAwMDAwNDU2MTExNDMxMDg4Njc5MDIzMjAwMDAwMDg5NjQ5Mjg2NDkwNDk1NjU1ODJfKTt9Cgkuc3Qze2ZpbGw6dXJsKCNTVkdJRF8wMDAwMDA5Mzg5OTc5NDI4NjYyMDMxMzA4MDAwMDAwNTM4Nzk4NzkxNjgwMzI5NzQyNV8pO30KCS5zdDR7bWFzazp1cmwoI1NWR0lEXzFfKTtmaWxsOnVybCgjU1ZHSURfMDAwMDAwODA5MTg1MzI5NTM1NTk0MjM5MTAwMDAwMDU0NDM2NjI2NDM1ODU3NDcwOTRfKTt9Cgkuc3Q1e2ZpbGw6IzAwMUQ2Qzt9Cjwvc3R5bGU+CjxnPgoJPGRlZnM+CgkJPGZpbHRlciBpZD0iQWRvYmVfT3BhY2l0eU1hc2tGaWx0ZXIiIGZpbHRlclVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeD0iMCIgeT0iMCIgd2lkdGg9IjMyIiBoZWlnaHQ9IjMyIj4KCQkJPGZlQ29sb3JNYXRyaXggIHR5cGU9Im1hdHJpeCIgdmFsdWVzPSIxIDAgMCAwIDAgIDAgMSAwIDAgMCAgMCAwIDEgMCAwICAwIDAgMCAxIDAiLz4KCQk8L2ZpbHRlcj4KCTwvZGVmcz4KCTxtYXNrIG1hc2tVbml0cz0idXNlclNwYWNlT25Vc2UiIHg9IjAiIHk9IjAiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgaWQ9IlNWR0lEXzFfIj4KCQk8ZyBjbGFzcz0ic3QwIj4KCQkJPGc+CgkJCQk8Zz4KCQkJCQk8cGF0aCBjbGFzcz0ic3QxIiBkPSJNNSwxOEgzdi00QzMsNy45LDcuOSwzLDE0LDNoOXYyaC05Yy01LDAtOSw0LTksOVYxOHoiLz4KCQkJCTwvZz4KCQkJCTxnPgoJCQkJCTxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik0xOCwyOUg5di0yaDljNSwwLDktNCw5LTl2LTRoMnY0QzI5LDI0LjEsMjQuMSwyOSwxOCwyOXoiLz4KCQkJCTwvZz4KCQkJPC9nPgoJCQkKCQkJCTxsaW5lYXJHcmFkaWVudCBpZD0iU1ZHSURfMDAwMDAxNzc0NDc2OTYxNzg2NDEyOTA3MzAwMDAwMDU5NjA2ODM1NDY4ODM4MzQyNDNfIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjgiIHkxPSIyOCIgeDI9IjE3IiB5Mj0iMjgiPgoJCQkJPHN0b3AgIG9mZnNldD0iMC4yIiBzdHlsZT0ic3RvcC1jb2xvcjojMDAwMDAwIi8+CgkJCQk8c3RvcCAgb2Zmc2V0PSIwLjkiIHN0eWxlPSJzdG9wLWNvbG9yOiMwMDAwMDA7c3RvcC1vcGFjaXR5OjAiLz4KCQkJPC9saW5lYXJHcmFkaWVudD4KCQkJPHJlY3QgeD0iOCIgeT0iMjYiIHN0eWxlPSJmaWxsOnVybCgjU1ZHSURfMDAwMDAxNzc0NDc2OTYxNzg2NDEyOTA3MzAwMDAwMDU5NjA2ODM1NDY4ODM4MzQyNDNfKTsiIHdpZHRoPSI5IiBoZWlnaHQ9IjQiLz4KCQkJCgkJCQk8bGluZWFyR3JhZGllbnQgaWQ9IlNWR0lEXzAwMDAwMTQzNTc0OTkyNjI1NjA3MjEwNTEwMDAwMDA1ODY1MDc2MDM0MjYwNDM0ODIxXyIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiIHgxPSIxNSIgeTE9IjQiIHgyPSIyNCIgeTI9IjQiPgoJCQkJPHN0b3AgIG9mZnNldD0iMC4xIiBzdHlsZT0ic3RvcC1jb2xvcjojMDAwMDAwO3N0b3Atb3BhY2l0eTowIi8+CgkJCQk8c3RvcCAgb2Zmc2V0PSIwLjgiIHN0eWxlPSJzdG9wLWNvbG9yOiMwMDAwMDAiLz4KCQkJPC9saW5lYXJHcmFkaWVudD4KCQkJPHJlY3QgeD0iMTUiIHk9IjIiIHN0eWxlPSJmaWxsOnVybCgjU1ZHSURfMDAwMDAxNDM1NzQ5OTI2MjU2MDcyMTA1MTAwMDAwMDU4NjUwNzYwMzQyNjA0MzQ4MjFfKTsiIHdpZHRoPSI5IiBoZWlnaHQ9IjQiLz4KCQk8L2c+Cgk8L21hc2s+CgkKCQk8bGluZWFyR3JhZGllbnQgaWQ9IlNWR0lEXzAwMDAwMDA1MjI0MzE0OTU0OTAxMDQ1MTQwMDAwMDExODE4OTYzODA0NzY0ODU2NzM5XyIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiIHgxPSItOS4wOTQ5NDdlLTEzIiB5MT0iMzIiIHgyPSIzMiIgeTI9IjMuODcyNDU4ZS0xMyI+CgkJPHN0b3AgIG9mZnNldD0iMC4xIiBzdHlsZT0ic3RvcC1jb2xvcjojMDhCREJBIi8+CgkJPHN0b3AgIG9mZnNldD0iMC45IiBzdHlsZT0ic3RvcC1jb2xvcjojMEY2MkZFIi8+Cgk8L2xpbmVhckdyYWRpZW50PgoJCgkJPHJlY3QgeT0iMCIgc3R5bGU9Im1hc2s6dXJsKCNTVkdJRF8xXyk7ZmlsbDp1cmwoI1NWR0lEXzAwMDAwMDA1MjI0MzE0OTU0OTAxMDQ1MTQwMDAwMDExODE4OTYzODA0NzY0ODU2NzM5Xyk7IiB3aWR0aD0iMzIiIGhlaWdodD0iMzIiLz4KCTxwYXRoIGNsYXNzPSJzdDUiIGQ9Ik0xNiwyMWMtMi44LDAtNS0yLjItNS01czIuMi01LDUtNXM1LDIuMiw1LDVTMTguOCwyMSwxNiwyMXogTTE2LDEzYy0xLjcsMC0zLDEuMy0zLDNzMS4zLDMsMywzczMtMS4zLDMtMwoJCVMxNy43LDEzLDE2LDEzeiIvPgoJPGNpcmNsZSBjbGFzcz0ic3Q1IiBjeD0iMjgiIGN5PSIxMCIgcj0iMiIvPgoJPGNpcmNsZSBjbGFzcz0ic3Q1IiBjeD0iNCIgY3k9IjIyIiByPSIyIi8+CjwvZz4KPC9zdmc+Cg==
    mediatype: image/svg+xml;base64
resources:
  - kind: CICSTSRegion
    displayName: CICS TS region
    description: Provision a CICS TS region on a z/OS endpoint
    playbook: provision.yml
    finalizer: deprovision.yml
    vars:
      - name: DFH_REGION_SYSID
        displayName: System identifier (SYSID)
        description: >-
           The system identifier (SYSID) for the CICS TS region. This must be 1-4 characters long.
        type: string
        required: true

      - name: DFH_REGION_APPLID
        displayName: Region application identifier (APPLID)
        description: >-
          The application identifier (APPLID) of the CICS TS region. This must be no longer than 8 characters.
        type: string
        required: true

      - name: DFH_ZFS_MOUNTPOINT
        displayName: zFS path
        description: >-
          The name and path of the root directory for CICS TS configuration files on z/OS UNIX. Specify a USS directory
          that CICS TS Operator is given access to write CICS TS configuration files.
        type: string
        required: true

      - name: USER
        displayName: z/OS User
        description: >-
          The z/OS user ID used to provision CICS data sets and submit jobs
        type: string
        required: true

      - name: DFH_CICS_HLQ
        displayName: HLQ for CICS load libraries
        description: >-
          The high level qualifier used in the data set names of CICS load libraries, hlq.SDFHAUTH and hlq.SDFHLOAD
          For example, if you specify the high level qualifier as CICSTS62.CICS, the data set names are C(CICSTS62.CICS.SDFHAUTH) and C(CICSTS62.CICS.SDFHLOAD).
        type: string
        required: false
        default: CICSTS62.CICS

      - name: DFH_REGION_HLQ
        displayName: HLQ for CICS region data sets
        description: >-
          The high level qualifier used in the names of CICS region data sets.
          The location of the region data sets to be created by using a template, for example,
          C(REGIONS.ABCD0001.<< data_set_name >>).
          The base location of the region data sets with a template.
        type: string
        required: false
        default: IBMUSER.REGIONS

      - name: DFH_CICS_LICENSE_DATA_SET
        displayName: CICS license data set
        description: >-
          The data set (SDFHLIC) containing the CICS license
        type: string
        required: false
        default: CICSTS62.CICS.SDFHLIC

      - name: DFH_CICS_USSHOME
        displayName: CICS USS home directory
        description: >-
           The name and path of the root directory for CICS TS files on z/OS UNIX.
        type: string
        required: false
        default: /usr/lpp/cicsts/cicsts62

      - name: DFH_REGION_DFLTUSER
        displayName: Default CICS user
        description: >-
          The RACF user ID of the default user, that is, the user whose security attributes are used to protect CICS resources in
          the absence of other, more specific user ID. The value is set to the DFLTUSER system initialization parameter of the CICS
          TS region.
        type: string
        required: false
        default: CICSUSER

      - name: DFH_CPSM_HLQ
        displayName: HLQ for CICSPlex SM data sets
        description: >-
          This parameter is required if you want to provision an SMSS.
          The high level qualifier used in the data set names of CICSPlex SM load libraries:
            hlq.SEYUAUTH
            hlq.SEYULOAD
        type: string
        required: false
        default: CICSTS62.CPSM

      - name: DFH_CMCI_PORT
        displayName: CMCI port
        description: >-
          The HTTP port for the CMCI connection. This parameter is required if you want to provision an SMSS
        type: integer
        required: false
