# (c) Copyright IBM Corp. 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Create a temporary file for the STC
  ansible.builtin.tempfile:
    state: file
  register: templated_stc
  delegate_to: localhost

- name: Template the STC
  ansible.builtin.template:
    src: STC.j2
    dest: "{{ templated_stc.path }}"
    mode: "600"
  delegate_to: localhost

- name: Copy the STC to z/OS
  environment: "{{ z_environment_vars }}"
  ibm.ibm_zos_core.zos_copy:
    src: "{{ templated_stc.path }}"
    dest: "{{ DFH_ZOS_STCJOBS }}({{ DFH_REGION_APPLID }})"
    remote_src: false
    backup: false
    force: true

- name: Delete the templated job tempfile for the STC
  ansible.builtin.file:
    state: absent
    path: "{{ templated_stc.path }}"
  delegate_to: localhost
