# (c) Copyright IBM Corp. 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Detect environment
  detect_environment:
  register: result

- name: Apply conventions
  ansible.builtin.include_role:
    name: conventions
    public: true

# Can't set ansible_python_interpreter in any module other than set_facts or include_vars
- name: Set interpreter
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ pyz }}/bin/python3"
