# (c) Copyright IBM Corp. 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Apply conventions
  ansible.builtin.include_role:
    name: conventions
    public: true
