# (c) Copyright IBM Corp. 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Create and initialize a new CICS CSD
  ansible.builtin.include_role:
    name: zos_job_submit_template
  vars:
    zos_job_submit_template_src: CCICSCCS.j2
    # Defining resources starting DFH gives a warning
    zos_job_submit_template_max_rc: 4
