# (c) Copyright IBM Corp. 2023,2024
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
argument_specs:
  main:
    options:
      k8s_managed:
        type: bool
        required: true
