# (c) Copyright IBM Corp. 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Start CICS
  environment: "{{ z_environment_vars }}"
  ibm.ibm_zos_core.zos_operator:
    cmd: START {{ DFH_REGION_APPLID }}

- name: Wait for CICS to start
  ansible.builtin.pause:
    seconds: "{{ start_cics_pause }}"

- name: Check if CICS is running for APPLID {{ DFH_REGION_APPLID }}
  environment: "{{ z_environment_vars }}"
  is_job_running:
    job_name: "{{ DFH_REGION_APPLID }}"
  register: is_cics_running

- name: Fail if CICS didn't start
  when: not is_cics_running.running
  ansible.builtin.fail:
    msg: CICS region did not start

- name: Report the CICS start outcome
  ansible.builtin.debug:
    msg: CICS region with APPLID {{ DFH_REGION_APPLID }} has been started.
