# (c) Copyright IBM Corp. 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Check if the zFS filesystem is still mounted
  ansible.builtin.stat:
    path: '{{ DFH_ZFS_MOUNTPATH }}/PROVISION_OK'
  register: mountpoint_exists

- name: Unmount zFS
  environment: "{{ z_environment_vars }}"
  when: mountpoint_exists.stat.exists
  ansible.builtin.command: "/usr/sbin/unmount -o immediate {{ DFH_ZFS_MOUNTPATH }}"
  changed_when: true

- name: Remove the zFS directory
  environment: "{{ z_environment_vars }}"
  ansible.builtin.file:
    path: "{{ DFH_ZFS_MOUNTPATH }}"
    state: absent

- name: Delete the zFS data set if it exists
  environment: "{{ z_environment_vars }}"
  ibm.ibm_zos_core.zos_mvs_raw:
    program_name: idcams
    auth: true
    dds:
      - dd_output:
          dd_name: sysprint
          return_content:
            type: text
      - dd_input:
          dd_name: sysin
          content:
            - " LISTC ENT('{{ DFH_ZFS }}')"
            - " IF LASTCC = 0 THEN DO"
            - "   DELETE {{ DFH_ZFS }}"
            - " END"
            - " ELSE IF LASTCC = 4 THEN SET MAXCC = 0"
  register: delete_dataset_response

- name: Log and fail
  when: >
    not delete_dataset_response.ret_code is defined or
    not delete_dataset_response.ret_code.code is defined or
    delete_dataset_response.ret_code.code > 0
  block:
    - name: Log the zFS deletion result
      ansible.builtin.fail:
        msg: "Deleting the zFS data set failed: {{ delete_dataset_response }}"
