# (c) Copyright IBM Corp. 2023,2024
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: "Stop CICS Region {{ DFH_REGION_APPLID | upper }}"
  environment: "{{ z_environment_vars }}"
  ibm.ibm_zos_cics.stop_region:
    job_name: "{{ DFH_REGION_APPLID | upper }}"
    timeout: 300
  register: cics_running
