# (c) Copyright IBM Corp. 2023,2024
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
galaxy_info:
  standalone: false
  role_name: start_cics_smss
  author: ibm
  description: Start CICS SMSS
  license: Apache
  min_ansible_version: '2.9'
  galaxy_tags: []
dependencies: []
