# (c) Copyright IBM Corp. 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
DFH_ZFS_MOUNTPATH: "{{ DFH_ZFS_MOUNTPOINT }}/{{ DFH_REGION_APPLID }}"
DFH_DFHCSD: "{{ DFH_REGION_HLQ }}.{{ DFH_REGION_APPLID }}.DFHCSD"
DFH_DFHGCD: "{{ DFH_REGION_HLQ }}.{{ DFH_REGION_APPLID }}.DFHGCD"
DFH_DFHLCD: "{{ DFH_REGION_HLQ }}.{{ DFH_REGION_APPLID }}.DFHLCD"
DFH_DFHTEMP: "{{ DFH_REGION_HLQ }}.{{ DFH_REGION_APPLID }}.DFHTEMP"
DFH_DFHINTRA: "{{ DFH_REGION_HLQ }}.{{ DFH_REGION_APPLID }}.DFHINTRA"
DFH_DFHLRQ: "{{ DFH_REGION_HLQ }}.{{ DFH_REGION_APPLID }}.DFHLRQ"
DFH_DFHBRNSF: "{{ DFH_REGION_HLQ }}.{{ DFH_REGION_APPLID }}.DFHBRNSF"
DFH_DFHAUXT: "{{ DFH_REGION_HLQ }}.{{ DFH_REGION_APPLID }}.DFHAUXT"
DFH_DFHBUXT: "{{ DFH_REGION_HLQ }}.{{ DFH_REGION_APPLID }}.DFHBUXT"
DFH_DFHDMPA: "{{ DFH_REGION_HLQ }}.{{ DFH_REGION_APPLID }}.DFHDMPA"
DFH_DFHDMPB: "{{ DFH_REGION_HLQ }}.{{ DFH_REGION_APPLID }}.DFHDMPB"
DFH_ZFS: "{{ DFH_REGION_HLQ }}.{{ DFH_REGION_APPLID }}.ZFS"
