# (c) Copyright IBM Corp. 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Check the SYSID is between 1 and 3 characters long
  when: (DFH_REGION_SYSID | length) == 0 or (DFH_REGION_SYSID | length) > 3
  ansible.builtin.set_fact:
    validation_error: SYSID '{{ DFH_REGION_SYSID }}' must be between 1 and 3 characters long

- name: Check the SYSID contains only acceptable characters
  when:
    - validation_error is not defined
    - DFH_REGION_SYSID is not regex("^[A-Z0-9@#\$]+$")
  ansible.builtin.set_fact:
    validation_error: SYSID '{{ DFH_REGION_SYSID }}' must only contain acceptable characters (A–Z, 0–9, @, {{ '#' }} , or $)
